# Generated by Django 3.1.5 on 2021-01-30 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_add_slug'),
        ('website', '0002_post_slug'),
    ]

    operations = [
    ]
