# Generated by Django 3.1.5 on 2021-01-30 23:28

from django.db import migrations
from django.utils.text import slugify

def add_slug(apps, schema_editor):
    Post = apps.get_model('website', 'Post')
    for post in Post.objects.all():
        post.slug = slugify(post.title)
        post.save()

class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_merge_20210130_2028'),
        ('website', '0003_add_slug'),
        ('website', '0002_post_slug'),
    ]

    operations = [
        migrations.RunPython(add_slug),
    ]
